# Generated by Django 5.1.7 on 2025-05-01 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
