# Generated by Django 5.1.7 on 2025-05-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_contactsubmission_campaign_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspiringStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='insp/img')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspstories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
