# Generated by Django 5.1.7 on 2025-05-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_inspiringstories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiringstories',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='inspiringstories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insp/'),
        ),
        migrations.AlterField(
            model_name='inspiringstories',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
