# Generated by Django 5.1.7 on 2025-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_inspiringstories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiringstories',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='inspiringstories',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
