# Generated by Django 5.1.7 on 2025-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_alter_inspiringstories_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
