# Generated by Django 5.1.7 on 2025-05-04 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ends_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
