# Generated by Django 5.1.7 on 2025-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_campaign_ends_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ends_date',
            field=models.DateTimeField(),
        ),
    ]
