# Generated by Django 5.1.7 on 2025-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_donationsettings_generalsettings_securitysettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationSettings',
        ),
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
        migrations.DeleteModel(
            name='SecuritySettings',
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
